name: Firebase Deploy
on:
  push:
    branches: 
      - gh-actions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - name: Install Dependencies
      working-directory: ./app
      run: npm install
    - name: Build
      working-directory: ./app
      run: npm run build
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: app/dist
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: gasless-20d13
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
